name: gitleaks
on:
  pull_request:
    branches:
      - develop
      - test
      - acc
      - main
  push:
    branches:
      - develop
      - test
      - acc
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *" # run once a day at 4 AM
  
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
