name: Mika ISO test build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on:
      - self-hosted
      - Arch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Removing old files from previous builds
      run: sudo rm -rf /home/luciousdev/actions-runner/_work/base-iso

    - name: Clone the repository
      run: git clone https://github.com/Mika-Project/base-iso.git /home/luciousdev/runner-tests/base-iso

    - name: cd into working directory
      run: cd /home/luciousdev/runner-tests/base-iso

    - name: Build the Arch ISO
      run: sudo mkarchiso -v -r .
