name: Mika ISO test build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone the REPO
      run: git clone https://github.com/Mika-Project/base-iso.git /home/lucy/runner-tests/base-iso

    - name: cd into working directory
      run: cd /home/lucy/runner-tests/base-iso

    - name: Run Command 2
      run: sudo mkarchiso -v -r .
