name: Mika ISO test build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: (Prerequisite) Removing old files if exists
      run: sudo rm -rf /home/lucy/actions-runner/_work/base-iso

    - name: Clone the repository
      run: git clone https://github.com/Mika-Project/base-iso.git /home/lucy/runner-tests/base-iso

    - name: cd into working directory
      run: cd /home/lucy/runner-tests/base-iso

    - name: Build the Arch ISO
      run: sudo mkarchiso -v -r .
